services:
  backend:
    build: .
    network_mode: "host"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build: ./logitrack-ui
    network_mode: "host"
    depends_on:
      - backend

# REMOVED: The networks block at the bottom is gone.